adding PR

diff --git a/.github/workflows/check-ts-errors.yml b/.github/workflows/check-ts-errors.yml
--- a/.github/workflows/check-ts-errors.yml
+++ b/.github/workflows/check-ts-errors.yml
@@ -29,31 +29,36 @@ jobs:
       run: |
         dmmulroyDir="error_templates/"
         mattpocockDir="ts-error-translator/packages/engine/errors/"
-        
+
         # Use diff to compare the directories and store the output in a file
         diff -rq "$dmmulroyDir" "$mattpocockDir" > directory_diff.txt
 
         # Check the exit code of diff (0 if no differences, 1 if differences found)
         if [ $? -eq 0 ]; then
-          echo "No differences found."
-        else
-          echo "Differences found:"
-          echo "$differences"
+              echo "No differences found."
+            else
+              echo "Differences found:"
+              cat directory_diff.txt  # Display the differences
 
-          # Create a branch and push the changes
-          git checkout -b branch-for-differences
-          git add .
-          git commit -m "Differences found"
-          git push origin branch-for-differences
+              # Create a branch and push the changes
+              git checkout -b branch-for-differences
+              git add .
+              git commit -m "Differences found"
+              git push origin branch-for-differences
 
-          # Create a pull request
-          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d '{
-            "title": "Differences Found",
-            "head": "branch-for-differences",
-            "base": "main",  # Adjust the target branch as needed
-            "body": "Differences were found between directories.",
-            "maintainer_can_modify": true
-          }' "https://api.github.com/repos/dmmulroy/better-ts-errors.nvim/pulls"
-          
-          exit 1  # Fail the workflow
-        fi
+              # Create a pull request
+              pr_response=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d '{
+                "title": "Differences Found",
+                "head": "branch-for-differences",
+                "base": "main",  # Adjust the target branch as needed
+                "body": "Differences were found between directories.",
+                "maintainer_can_modify": true
+              }' "https://api.github.com/repos/dmmulroy/better-ts-errors.nvim/pulls")
+
+              pr_url=$(echo "$pr_response" | jq -r .html_url)
+
+              # Output the URL of the created PR
+              echo "PR created: $pr_url"
+
+              exit 1  # Fail the workflow
+            fi
